apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-logic 
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: sa-logic
  minReadySeconds: 15 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata: 
      labels:
        app: sa-logic 
    spec:
      containers:
        - image: yashthakkar248/sentiment-analysis-logic
          imagePullPolicy: Always 
          name: sa-logic
          ports:
            - containerPort: 5000