apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web-app
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: sa-web-app
  minReadySeconds: 15 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata: 
      labels:
        app: sa-web-app 
    spec:
      containers:
        - image: yashthakkar248/sentiment-analysis-web-app
          imagePullPolicy: Always 
          name: sa-logic
          env:
            - name: SA_LOGIC_API_URL
              value: "http://sa-logic"
          ports:
            - containerPort: 8080